"use client";
import Link from "next/link";
import { useSearchParams } from "next/navigation";
import { useMemo, useState } from "react";
import type { University } from "../lib/types";

const countryGroups:Record<string,string[]>={"영국":["United Kingdom","UK","England","Scotland","Wales"],"유럽":["United Kingdom","UK","England","Scotland","Wales","France","Germany","Spain","Italy","Netherlands","Sweden","Denmark","Finland","Norway","Switzerland","Austria","Belgium","Ireland"],"북미":["United States","USA","Canada","Mexico"],"아시아":["Japan","China","Singapore","Hong Kong","Taiwan","South Korea"],"오세아니아":["Australia","New Zealand"]};
const tests=["IELTS Academic","TOEFL iBT","Cambridge CAE/CPE","PTE Academic","Duolingo English Test","Oxford ELLT"];
const CURRENCY_TO_KRW:Record<string,number>={EUR:1600,GBP:1900,DKK:215,CHF:1700,NOK:140,SEK:145,USD:1380,CAD:1010,SGD:1070,HKD:176,TWD:43,BRL:255};
type CostSummary={krw:number;display:string;components:string[]};
function matchesTest(stored:unknown,selected:string){const value=String(stored??"").toLowerCase();const aliases:Record<string,string[]>={"IELTS Academic":["ielts"],"TOEFL iBT":["toefl"],"Cambridge CAE/CPE":["cambridge","cae","cpe"],"PTE Academic":["pte","pearson"],"Duolingo English Test":["duolingo"],"Oxford ELLT":["oxford","ellt"]};return(aliases[selected]??[]).some((alias)=>value.includes(alias));}
function toNumber(value:unknown){if(value===null||value===undefined||value==="")return null;if(typeof value==="number")return Number.isFinite(value)?value:null;if(typeof value!=="string")return null;const match=value.replace(/,/g,"").match(/\d+(?:\.\d+)?/);if(!match)return null;const parsed=Number(match[0]);return Number.isFinite(parsed)?parsed:null;}
function detectCurrency(row:Record<string,unknown>){const explicit=String(row.currency??"").trim().toUpperCase();if(CURRENCY_TO_KRW[explicit])return explicit;const text=Object.values(row).join(" ").toUpperCase();if(/€|EUR/.test(text))return"EUR";if(/£|GBP/.test(text))return"GBP";if(/DKK/.test(text))return"DKK";if(/CHF/.test(text))return"CHF";if(/NOK/.test(text))return"NOK";if(/SEK/.test(text))return"SEK";if(/SGD/.test(text))return"SGD";if(/HKD/.test(text))return"HKD";if(/TWD/.test(text))return"TWD";if(/CAD/.test(text))return"CAD";if(/BRL/.test(text))return"BRL";if(/USD|\$/.test(text))return"USD";return null;}
function toSemester(amount:number,period:unknown){const label=String(period??"").toLowerCase();if(/month|monthly|per month|월/.test(label))return amount*5;if(/week|weekly|per week|주/.test(label))return amount*20;if(/academic year|full year|annual|per year|year|연간|1년|until/.test(label))return amount/2;return amount;}
function costCategory(row:Record<string,unknown>){const text=Object.entries(row).filter(([key])=>!/url|source|evidence|title/i.test(key)).map(([key,value])=>`${key} ${String(value??"")}`).join(" ").toLowerCase();if(/housing|accommodation|dorm|residence|hall|lodging|기숙|숙소|주거/.test(text))return"housing";if(/living|meal|food|transport|book|insurance|incidentals|생활|식비|교통|보험/.test(text))return"living";if(/tuition|registration|등록금|학비/.test(text))return"tuition";return"other";}
function amountFromRow(row:Record<string,unknown>){for(const key of["amount_max","amount_min","cost_max","cost_min","price_max","price_min","amount","cost","fee","price"]){const value=toNumber(row[key]);if(value!==null)return value;}const text=Object.values(row).join(" ");if(/waived|exempt|free|면제/.test(text)&&/tuition|registration|등록금|학비/i.test(text))return 0;return null;}
function semesterCost(u:University):CostSummary|null{const p=u.exchange_programs?.[0];const rows=[...(p?.estimated_costs??[]),...(p?.housing_options??[])];const selected=new Map<string,{krw:number;label:string}>();for(const row of rows){const amount=amountFromRow(row);if(amount===null)continue;const currency=detectCurrency(row)??(amount===0?"KRW":null);const rate=currency==="KRW"?1:CURRENCY_TO_KRW[currency??""];if(!currency||!rate)continue;const category=costCategory(row);if(category==="other")continue;const period=row.billing_period??row.reference_period??row.period;const semesterAmount=toSemester(amount,period);const krw=semesterAmount*rate;const label=`${category}: ${currency} ${Math.round(semesterAmount).toLocaleString()}${period?` (${String(period)})`:""}`;const existing=selected.get(category);if(!existing||krw<existing.krw)selected.set(category,{krw,label});}const components=[...selected.values()];if(!components.length)return null;if(!selected.has("housing")&&!selected.has("living"))return null;const krw=components.reduce((sum,item)=>sum+item.krw,0);return{krw,display:`약 ${Math.round(krw/10000).toLocaleString()}만원`,components:components.map((item)=>item.label)};}

export function UniversityResults({universities}:{universities:University[]}){
  const params=useSearchParams();
  const [countries,setCountries]=useState((params.get("countries")??"").split(",").filter(Boolean));
  const [languageTest,setLanguageTest]=useState(params.get("languageTest")??"");
  const [languageScore,setLanguageScore]=useState(Number(params.get("languageScore")??0));
  const [budget,setBudget]=useState(Number(params.get("budget")??15000000));
  const [budgetActive,setBudgetActive]=useState(params.has("budget"));
  const [housingOnly,setHousingOnly]=useState(params.get("housing")==="true");
  const [filterOpen,setFilterOpen]=useState(false);const [selected,setSelected]=useState<string[]>([]);
  const toggleCountry=(country:string)=>setCountries((current)=>current.includes(country)?current.filter((item)=>item!==country):[...current,country]);
  const reset=()=>{setCountries([]);setLanguageTest("");setLanguageScore(0);setBudget(15000000);setBudgetActive(false);setHousingOnly(false);};
  const filtered=useMemo(()=>universities.filter((item)=>{const countryMatch=!countries.length||countries.some((group)=>(countryGroups[group]??[group]).includes(item.country));const housingMatch=!housingOnly||Boolean(item.exchange_programs?.[0]?.housing_options?.length);const requirements=item.exchange_programs?.[0]?.language_requirements??[];const matching=languageTest?requirements.filter((row)=>matchesTest(row.test_type,languageTest)):[];const languageMatch=!languageTest||(matching.length>0&&matching.some((row)=>{const required=toNumber(row.overall_score);return required!==null&&languageScore>=required;}));const cost=semesterCost(item);return countryMatch&&housingMatch&&languageMatch&&(!budgetActive||(cost!==null&&cost.krw<=budget));}),[universities,countries.join(","),housingOnly,languageTest,languageScore,budget,budgetActive]);
  const toggleCompare=(id:string)=>setSelected((current)=>current.includes(id)?current.filter((item)=>item!==id):current.length<3?[...current,id]:current);
  return <>
    <section className="list-hero result-hero"><p className="eyebrow">PARTNER UNIVERSITIES</p><h1>{params.toString()?"내 조건에 맞는 대학":"교환대학 목록"}</h1><p><b>{filtered.length}개</b> 대학을 확인할 수 있어요. 이 페이지에서 바로 필터를 수정할 수 있습니다.</p></section>
    <section className="active-conditions"><span>현재 필터</span><b>{countries.length?countries.join(" · "):"전체 국가"}</b>{languageTest&&<b>{languageTest} {languageScore}</b>}{budgetActive&&<b>한 학기 약 {Math.round(budget/10000).toLocaleString()}만원 이하</b>}{housingOnly&&<b>기숙사 정보 있음</b>}<button className="edit-filter" onClick={()=>setFilterOpen(!filterOpen)}>{filterOpen?"필터 닫기":"필터 수정"}</button><button className="reset-filter" onClick={reset}>전체 초기화</button></section>
    {filterOpen&&<section className="inline-filter"><div><label>관심 국가</label><div className="multi-choice">{Object.keys(countryGroups).map((country)=><button key={country} className={countries.includes(country)?"selected":""} onClick={()=>toggleCountry(country)}>{country}</button>)}</div></div><label>어학시험<select value={languageTest} onChange={(e)=>setLanguageTest(e.target.value)}><option value="">시험 조건 없음</option>{tests.map((test)=><option key={test}>{test}</option>)}</select></label><label>보유 점수<input type="number" min="0" step="0.5" value={languageScore} disabled={!languageTest} onChange={(e)=>setLanguageScore(Number(e.target.value))}/></label><label>한 학기 비용 상한<input type="range" min="3000000" max="20000000" step="500000" value={budget} onChange={(e)=>{setBudget(Number(e.target.value));setBudgetActive(true);}}/><b>{budgetActive?`약 ${Math.round(budget/10000).toLocaleString()}만원`:"미적용"}</b></label><label className="inline-check"><input type="checkbox" checked={housingOnly} onChange={(e)=>setHousingOnly(e.target.checked)}/> 기숙사 정보가 있는 대학만</label></section>}
    <section className="university-grid">{filtered.map((item,index)=>{const cost=semesterCost(item);return <article className="university-card" key={item.id}><div className={`card-visual visual-${index%3} ${item.image_url?"has-photo":""}`} style={item.image_url?{backgroundImage:`linear-gradient(180deg,transparent,rgba(10,30,55,.72)),url(${item.image_url})`}:undefined}><span>{item.image_url?"":item.city.slice(0,1)}</span><small>{item.city}</small></div><div className="card-content"><div className="card-top"><p>{item.country} · {item.city}</p><label className="compare-check"><input type="checkbox" checked={selected.includes(item.id)} onChange={()=>toggleCompare(item.id)}/> 비교</label></div><h2>{item.university_name}</h2><div className="chips"><span>{item.exchange_programs?.[0]?.academic_year??"최신 학년도"}</span><span>{cost===null?"비용 확인 중":`한 학기 ${cost.display}`}</span></div><p className="summary">{item.summary}</p><Link href={`/universities/${item.id}`}>상세 정보 보기 <b>→</b></Link></div></article>;})}</section>
    {!filtered.length&&<section className="no-results"><h2>현재 조건에 맞는 대학이 없어요.</h2><p>위의 필터를 수정하거나 초기화해 보세요.</p><button onClick={reset}>필터 초기화</button></section>}
    {selected.length>0&&<div className="compare-bar"><div><b>{selected.length}개 대학 선택</b><span>최대 3개까지 비교할 수 있어요.</span></div><button onClick={()=>setSelected([])}>선택 초기화</button><Link href={`/compare?ids=${selected.join(",")}`}>선택 대학 비교하기 →</Link></div>}
  </>;
}
